version: "3.8"

services:
  node-app:
    build:
      context: .
      args:
        NODE_ENV: "development"
    ports:
      - "9229:9229"
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev

volumes:
  node_modules:
